### ISSUE TITLE
Add release notes

### ISSUE THREAD

**Issue by dtolnay** [unicode-rs/unicode-xid#5]
I am interested in the difference between 0.0.4 and 0.1.0.

https://github.com/unicode-rs/unicode-xid/releases

**Comment by SimonSapin** [comment]
IIRC there isn’t one. The motivation for 0.1.0 is explained at https://github.com/servo/servo/issues/15224.

**Comment by SimonSapin** [comment]
I’ve added tags based on matching commit dates with crates.io publication dates. The diff is https://github.com/unicode-rs/unicode-xid/compare/v0.0.4...v0.1.0
